#https://developers.home-assistant.io/docs/add-ons/configuration

name: "Python Protocol Gateway"
description: "Python Protocol Gateway"
version: "1.0.0"
slug: "ppg"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
#priveleged to access usb devices
usb: true
uart: true
url: "https://github.com/HotNoob/PythonProtocolGateway"
options: 
  log_level: DEBUG
schema:
  log_level: list(debug|info|warning|error)